apiVersion: v1
kind: ServiceAccount
metadata:
  name: golang-build-bot
secrets:
  - name: basic-user-pass
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: golang-from-source
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: golang-build-bot
          source:
            git:
              url: https://github.com/mchmarny/simple-app.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker.io/justin2997/golang-from-source:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/justin2997/golang-from-source:latest
            imagePullPolicy: Always