apiVersion: v1
kind: ServiceAccount
metadata:
  name: golang-build-bot
secrets:
  - name: basic-user-pass
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: golang-from-source
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: golang-build-bot
          source:
            git:
              url: https://github.com/Justin2997/Knative-Build-GitHub-Exemple.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker.io/{DOCKER_USERNAME}/golang-from-source:latest
              - name: DOCKERIMAGE
                value: /workspace/golang/Dockerfile
      revisionTemplate:
        spec:
          container:
            image: docker.io/{DOCKER_USERNAME}/golang-from-source:latest
            imagePullPolicy: Always